# -*- mode:org -*-
#+TITLE: Call C from Fortran
#+Author: Vijay
#+email: vijay.gopal.c@gmail.com


* Calling C from Fortran Tutorial

** Introduction

Understanding the standard way of calling C from Fortran is the goal of this
project. The interface should be standard across compilers and platforms.

** TODO [3/3] Basics

*** C code

A simple instance for the usage of such an interface can be described
via a simple C code that calculates the binomial coefficient.

#+begin_src c :main no :tangle cfunctions.c
#include <stdio.h>
#include <math.h>
#include <stdint.h>

double logbinom(float n, float k){
    return(lgamma(n+1)-lgamma(n-k+1)-lgamma(k+1));
}

void binom(float *n, float *k, float *res){
    *res = 0.0;
    *res = (exp(logbinom(*n,*k)));
}

#+end_src

This function accepts two double (real) numbers \( n, k\) and returns a double
pointer containing the value of the binomial.

*** [X] F interface

Now the interface in fortram which describes the input and output variables
which correspond to the c function above.

#+begin_src fortran :main no :tangle fmain.f90
      module cfunctions
      use, intrinsic :: ISO_C_BINDING
      interface
         subroutine cbinom(n, k, res) bind(C, name='binom')
         import C_FLOAT
         real(kind=C_FLOAT) :: n
         real(kind=C_FLOAT) :: k
         real(kind=C_FLOAT) :: res
         end subroutine cbinom
      end interface
      end module cfunctions
#+end_src

This function ~binom~ has been interfaced to Fortran with the name ~cbinom~
which accepts two real numbers \(n,k\) and returns a pointer to a real number
containing the binomial coefficient.

*** [X] F program

Now the main program can call the C function.

#+begin_src fortran :main no :tangle fmain.f90
      program main
      use, intrinsic :: ISO_C_BINDING
      use cfunctions
      implicit none
      real :: n   = 4.0d0
      real :: k   = 2.0d0
      real :: res =-1.0d0
      print *,n,k,res
      call cbinom(n, k, res)
      print *,n,k,res
      end program main
#+end_src

*** [X] Compiling and Running

#+begin_src shell
gcc -c cfunctions.c
gfortran fmain.f90 cfunctions.o -o main.exe -I/usr/local/include -L/usr/local/lib -lgfortran
./main.exe
#+end_src

#+RESULTS:
| 4.0 | 2.0 | -1.0 |
| 4.0 | 2.0 |  6.0 |

** TODO [0/5] Passing arrays

*** [ ] Passing 1D int array

*** [ ] Passing 2D int array

*** [ ] Passing 1D float array

*** [ ] Passing 2D float array

*** [ ] Passing nD <type> array
